### ISSUE TITLE
Split in multiple lines when multiple selectors

### ISSUE THREAD

**Issue by rsm-gh** [rsm-gh/cssmax#1]
Split in multiple lines when multiple selectors

Current decompression:
```css
div.home-slide > div:first-child > h2, div.home-slide > div:first-child > p {
    margin-top: 0;
    padding-top: 0
}
```

Expected:
```css
div.home-slide > div:first-child > h2,
div.home-slide > div:first-child > p {
    margin-top: 0;
    padding-top: 0
}
```
