### ISSUE TITLE
Remove ending space in parentesis

### ISSUE THREAD

**Issue by rsm-gh** [rsm-gh/cssmax#2]
Current examples:
```css
@media(min-width:1292px ) {
    #div-promo-text {
        margin-bottom: 6rem 
    }
}

div.home-slide > div:nth-child(2) {
    max-width: calc(70% - 3rem );
    padding-left: 2rem;
    text-align: center
}
```

Expected:
```css
@media(min-width:1292px) {
    #div-promo-text {
        margin-bottom: 6rem 
    }
}

div.home-slide > div:nth-child(2) {
    max-width: calc(70% - 3rem);
    padding-left: 2rem;
    text-align: center
}
```
